<?xml version="1.0" encoding="utf-8"?><Database Name="vasialek_onbalance" Class="ObLogDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=184.173.226.203;Initial Catalog=vasialek_onbalance;User ID=vasialek_onbalance_user" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="vasialek_onbalanceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="vasialek_onbalance_user.ob_log" Member="ObLogs">
    <Type Name="ObLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Thread" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Logger" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="Exception" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>