#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBalance.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="vasialek_onbalance")]
	public partial class SizeConvertorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSizeConvertor(SizeConvertor instance);
    partial void UpdateSizeConvertor(SizeConvertor instance);
    partial void DeleteSizeConvertor(SizeConvertor instance);
    #endregion
		
		public SizeConvertorDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["vasialek_onbalanceConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SizeConvertorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SizeConvertorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SizeConvertorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SizeConvertorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SizeConvertor> SizeConvertors
		{
			get
			{
				return this.GetTable<SizeConvertor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="vasialek_onbalance_user.size_convertor")]
	public partial class SizeConvertor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _category_id;
		
		private string _euro_size;
		
		private string _uk_size;
		
		private string _us_size;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncategory_idChanging(int value);
    partial void Oncategory_idChanged();
    partial void Oneuro_sizeChanging(string value);
    partial void Oneuro_sizeChanged();
    partial void Onuk_sizeChanging(string value);
    partial void Onuk_sizeChanged();
    partial void Onus_sizeChanging(string value);
    partial void Onus_sizeChanged();
    #endregion
		
		public SizeConvertor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int NOT NULL")]
		public int category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this.Oncategory_idChanging(value);
					this.SendPropertyChanging();
					this._category_id = value;
					this.SendPropertyChanged("category_id");
					this.Oncategory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_euro_size", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string euro_size
		{
			get
			{
				return this._euro_size;
			}
			set
			{
				if ((this._euro_size != value))
				{
					this.Oneuro_sizeChanging(value);
					this.SendPropertyChanging();
					this._euro_size = value;
					this.SendPropertyChanged("euro_size");
					this.Oneuro_sizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uk_size", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string uk_size
		{
			get
			{
				return this._uk_size;
			}
			set
			{
				if ((this._uk_size != value))
				{
					this.Onuk_sizeChanging(value);
					this.SendPropertyChanging();
					this._uk_size = value;
					this.SendPropertyChanged("uk_size");
					this.Onuk_sizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_size", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string us_size
		{
			get
			{
				return this._us_size;
			}
			set
			{
				if ((this._us_size != value))
				{
					this.Onus_sizeChanging(value);
					this.SendPropertyChanging();
					this._us_size = value;
					this.SendPropertyChanged("us_size");
					this.Onus_sizeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
